Add error handling for logger.Sync
atlassian/ctrl pull request #27
Opened 2018-08-17 08:56 UTC by scottgreenup

I thought we could handle this error, just in case we might get a problem in the future with syncing logs. Also removes a nolint comment, and a why-we-did-that comment. Thoughts?

2018-08-17 09:20 UTC, ash2k requested changes

2018-08-17 09:20 UTC, ash2k commented on app/app.go
> +			fmt.Printf("Failed to flush (AKA sync) remaining logs: %s\n", err.Error())
`fmt.Fprintf(os.Stderr, "Failed to flush (AKA sync) remaining logs: %v\n", err)`

Note the `%v` change too.

2018-08-19 04:08 UTC, ash2k commented
You don't want to print it to stderr for some reason (see my first comment)?

2018-08-19 06:13 UTC, scottgreenup commented
Sorry, it was late at night and I've misread your comment. I will update with stderr.

2018-09-10 04:52 UTC, ash2k approved these changes

2018-09-10 04:52 UTC, merged